import { CardProps } from "../types/CardProps";
import {
  IconClipboardData,
  IconBuildingBank,
  IconChefHat,
  IconDeviceTv,
  IconConfetti,
  IconCar,
  IconBeach,
  IconDeviceImac,
  IconStereoGlasses,
  IconMicrophone2,
  IconCaravan,
  IconRun
} from "@tabler/icons-react";

export const choiceCards: CardProps[] = [
  {
    title: "Go on holiday",
    description: "Go on holiday to somewhere nice",
    icon: <IconBeach size={100} />,
    effect: "happiness",
    effectValue: 100,
    category: "choice",
    cost: 100,
  },
  {
    title: "Employer training",
    description:
      "Your employer offers you training, this will increase your skills and make you more valuable increasing your salary",
    icon: <IconClipboardData size={100} />,
    effect: "cash",
    effectValue: 100,
    category: "choice",
    cost: 100,
  },
  {
    title: "Employer training",
    description:
      "Your employer offers you training, this will increase your skills and make you more valuable increasing your salary",
    icon: <IconClipboardData size={100} />,
    effect: "cash",
    effectValue: 100,
    category: "choice",
    cost: 100,
  },
  {
    title: "Contribute to pension",
    description:
      "You decide to contribute to your pension, this will increase your pension pot",
    icon: <IconBuildingBank size={100} />,
    effect: "cash",
    effectValue: 100,
    category: "choice",
    cost: 100,
  },
  {
    title: "Contribute to pension",
    description:
      "You decide to contribute to your pension, this will increase your pension pot",
    icon: <IconBuildingBank size={100} />,
    effect: "pension",
    effectValue: 100,
    category: "choice",
    cost: 100,
  },
  {
    title: "Contribute to pension",
    description:
      "You decide to contribute to your pension, this will increase your pension pot",
    icon: <IconBuildingBank size={100} />,
    effect: "pension",
    effectValue: 100,
    category: "choice",
    cost: 100,
  },
  {
    title: "Contribute to pension",
    description:
      "You decide to contribute to your pension, this will increase your pension pot",
    icon: <IconBuildingBank size={100} />,
    effect: "pension",
    effectValue: 100,
    category: "choice",
    cost: 100,
  },
  {
    title: "Contribute to pension",
    description:
      "You decide to contribute to your pension, this will increase your pension pot",
    icon: <IconBuildingBank size={100} />,
    effect: "pension",
    effectValue: 100,
    category: "choice",
    cost: 100,
  },
  {
    title: "Contribute to pension",
    description:
      "You decide to contribute to your pension, this will increase your pension pot",
    icon: <IconBuildingBank size={100} />,
    effect: "pension",
    effectValue: 100,
    category: "choice",
    cost: 100,
  },
  {
    title: "Contribute to pension",
    description:
      "You decide to contribute to your pension, this will increase your pension pot",
    icon: <IconBuildingBank size={100} />,
    effect: "pension",
    effectValue: 100,
    category: "choice",
    cost: 100,
  },
  {
    title: "Contribute to pension",
    description:
      "You decide to contribute to your pension, this will increase your pension pot",
    icon: <IconBuildingBank size={100} />,
    effect: "pension",
    effectValue: 100,
    category: "choice",
    cost: 100,
  },
  {
    title: "Contribute to pension",
    description:
      "You decide to contribute to your pension, this will increase your pension pot",
    icon: <IconBuildingBank size={100} />,
    effect: "pension",
    effectValue: 100,
    category: "choice",
    cost: 100,
  },
  {
    title: "Contribute to pension",
    description:
      "You decide to contribute to your pension, this will increase your pension pot",
    icon: <IconBuildingBank size={100} />,
    effect: "pension",
    effectValue: 100,
    category: "choice",
    cost: 100,
  },
  {
    title: "Eat out",
    description: "You decide to eat out, this will make you happy",
    icon: <IconChefHat size={100} />,
    effect: "happiness",
    effectValue: 100,
    category: "choice",
    cost: 100,
  },
  {
    title: "Eat out",
    description: "You decide to eat out, this will make you happy",
    icon: <IconChefHat size={100} />,
    effect: "happiness",
    effectValue: 100,
    category: "choice",
    cost: 100,
  },
  {
    title: "Eat out",
    description: "You decide to eat out, this will make you happy",
    icon: <IconChefHat size={100} />,
    effect: "happiness",
    effectValue: 100,
    category: "choice",
    cost: 100,
  },
  {
    title: "Eat out",
    description: "You decide to eat out, this will make you happy",
    icon: <IconChefHat size={100} />,
    effect: "happiness",
    effectValue: 100,
    category: "choice",
    cost: 100,
  },
  {
    title: "Buy a tv",
    description: "You decide to buy a tv, this will make you happy",
    icon: <IconDeviceTv size={100} />,
    effect: "happiness",
    effectValue: 100,
    category: "choice",
    cost: 200,
  },
  {
    title: "Buy a car",
    description: "You decide to buy a car, this will make you happy",
    icon: <IconCar size={100} />,
    effect: "happiness",
    effectValue: 100,
    category: "choice",
    cost: 1000,
  },
  {
    title: "Buy a computer",
    description: "You decide to buy a computer, this will make you happy",
    icon: <IconDeviceImac size={100} />,
    effect: "happiness",
    effectValue: 100,
    category: "choice",
    cost: 500,
  },
  {
    title: "Night out",
    description: "You decide to go on a night out, this will make you happy",
    icon: <IconConfetti size={100} />,
    effect: "happiness",
    effectValue: 100,
    category: "choice",
    cost: 100,
  },
  {
    title: "Night out",
    description: "You decide to go on a night out, this will make you happy",
    icon: <IconConfetti size={100} />,
    effect: "happiness",
    effectValue: 100,
    category: "choice",
    cost: 100,
  },
  {
    title: "Night out",
    description: "You decide to go on a night out, this will make you happy",
    icon: <IconRun size={100} />,
    effect: "happiness",
    effectValue: 100,
    category: "choice",
    cost: 100,
  },
  {
    title: "Night out",
    description: "You decide to go on a night out, this will make you happy",
    icon: <IconRun size={100} />,
    effect: "happiness",
    effectValue: 100,
    category: "choice",
    cost: 100,
  },
  {
    title: "Road trip",
    description: "You decide to go on a road trip, this will make you happy",
    icon: <IconCaravan size={100} />,
    effect: "happiness",
    effectValue: 100,
    category: "choice",
    cost: 200,
  },
  {
    title: "Concert",
    description: "You decide to go to a concert, this will make you happy",
    icon: <IconMicrophone2 size={100} />,
    effect: "happiness",
    effectValue: 100,
    category: "choice",
    cost: 100,
  },
  {
    title: "Concert",
    description: "You decide to go to a concert, this will make you happy",
    icon: <IconMicrophone2 size={100} />,
    effect: "happiness",
    effectValue: 100,
    category: "choice",
    cost: 100,
  },
  {
    title: "Watch movie",
    description: "You decide to go to a cenima, this will make you happy",
    icon: <IconStereoGlasses stroke={2} size={100} />,
    effect: "happiness",
    effectValue: 100,
    category: "choice",
    cost: 100,
  },
  {
    title: "Watch movie",
    description: "You decide to go to a cenima, this will make you happy",
    icon: <IconStereoGlasses stroke={2} size={100} />,
    effect: "happiness",
    effectValue: 100,
    category: "choice",
    cost: 100,
  },{
    title: "Watch movie",
    description: "You decide to go to a cenima, this will make you happy",
    icon: <IconStereoGlasses stroke={2} size={100} />,
    effect: "happiness",
    effectValue: 100,
    category: "choice",
    cost: 100,
  },
];
